### PR TITLE
Fixed hex color picker in material 3 demo

### LINKED ISSUE #2577: [material_3_demo] Color picker not working since Flutter 3.26+
With the current version of the color picker, the hex codes for the colors are not calculated correctly.

Image

Image

The SnackBar should show and copy the correct color.

### PR DESCRIPTION
**Pull request by Navil**
This pull request fixes the problem where the color picker wasn't handling hex values correctly.

Image
</br>
Old:
</br>
Image
</br>
New:
</br>
image

</br>
</br>
Fixes #2577

### CODE REVIEW

File: material_3_demo/lib/color_box.dart [hunk 1]
```diff
@@ -94,4 +93,9 @@ class _ColorBoxState extends State<ColorBox> {
       ),
     );
   }
+
+  String colorChannelToHex(double value) {
```
Comment (kevmoo) [inline material_3_demo/lib/color_box.dart:97]: Make this private, please

File: material_3_demo/lib/color_box.dart [hunk 2]
```diff
@@ -69,14 +69,13 @@ class _ColorBoxState extends State<ColorBox> {
...
-                      String hex = '#';
                       final c = widget.color;
-                      // Will change from int 0-255 to double 0.0-1.0 in 3.26+
-                      // The properties also change from red/green/blue to r/g/b
-                      // hex += (c.[r g b] * 255.0).round().toRadixString(16).padLeft(2, '0');
-                      hex += c.r.round().toRadixString(16).padLeft(2, '0');
-                      hex += c.g.round().toRadixString(16).padLeft(2, '0');
-                      hex += c.b.round().toRadixString(16).padLeft(2, '0');
+
+                      String hex = '#';
```
Comment (kevmoo) [inline material_3_demo/lib/color_box.dart:74]: make this final and just do the addition one after another.

**Comment by kevmoo** [comment]
also please rebase to get this running on CI! 😄

**Comment by kevmoo** [comment]
I got you! 😄

**Review by kevmoo — APPROVED** [review]

**Comment by kevmoo** [comment]
@domesticmouse would you review, approve, and do the auto-submit dance 🙏

**Comment by kevmoo** [comment]
Thanks @Navil ! it works! https://flutter.github.io/samples/web/material_3_demo/
